### ISSUE TITLE
Ferocity Timer Not Starting From Bush, Causing Permanent Stack

### ISSUE THREAD

**Issue by ArdaSenyurek** [ArdaSenyurek/Rengar-Bugs#14]
**Description:**  
Ferocity timer behavior differs from pre-rescript logic.  
Before the rescript:  
- If Rengar had 0 Ferocity and the timer wasn’t ticking, attacking from bush would **start the timer immediately** during AA windup, granting 1 stack even if canceled.  

Now:  
- Canceling an AA from bush before it lands prevents the timer from starting.  
- Rengar gains **1 Ferocity permanently** that only disappears after casting Q/W/E.  
- However, there’s a small delay before it’s removed, allowing him to cast Q or E and “cheat” out 4 Ferocity.  

[Video evidence](https://www.youtube.com/watch?v=g9DUzRWLyao)

**Expected Behavior:**  
Ferocity timer should start immediately upon attack windup from bush, consistent with previous logic.

**Comment by AuNorak** [comment]
This should be fixed, please verify

**Comment by ArdaSenyurek** [comment]
[video1](https://github.com/user-attachments/assets/0995e35b-7410-4bfd-8a6b-2e351ebc5d66)

[video2](https://github.com/user-attachments/assets/352ebdcb-7a34-40f8-aa40-3ede02b94b0c)

[video3](https://github.com/user-attachments/assets/b1c059ec-b6a1-4544-9ac1-359635247052)

- **Combat timer** still doesn't kick in -> causes permanent purple stack
- Also, some weird **instant expire** of Purple stack at the beginning of the game. Maybe practice tool related, but I didn't touch any Practice tool features before doing something.

**Comment by BACKSTAB44** [comment]
Fixed.
